# Generated by Django 5.1.1 on 2024-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sliders',
            new_name='Slide',
        ),
    ]
