# Generated by Django 5.1.1 on 2024-10-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, default='Описания коллекции', null=True, verbose_name='Описания')),
                ('image', models.ImageField(upload_to='photos/collections/%Y/%m/', verbose_name='photo Коллекции')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='TypeCarpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Тип ковра')),
            ],
            options={
                'verbose_name': 'Тип ковра',
                'verbose_name_plural': 'Типы ковров',
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код Ковра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/carpets/%Y/%m/', verbose_name='Изображения')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('roll', models.BooleanField(default=False, verbose_name='Рулон')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpets', to='catalog.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Ковер',
                'verbose_name_plural': 'Ковры',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.typecarpet', verbose_name='Тип ковра'),
        ),
    ]
